# Generated by Django 3.2.11 on 2022-01-31 05:33

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_auto_20220131_0533'),
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='Answered'),
        ),
        migrations.AddField(
            model_name='query',
            name='document',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='filer.file'),
        ),
    ]
